"""
TEST FILE: Advanced Code Analysis Features
==========================================
Use this file to test the world-class Code Scanner capabilities:
1. Semantic Code Analysis (AST parsing)
2. Dependency Vulnerability Scanning
3. Code Complexity Metrics
4. AI-Generated Code Detection
5. Code Fraud Detection

IMPORTANT: This is a TEST FILE with intentional vulnerabilities.
DO NOT use this code in production!
"""

import pickle
import os
import subprocess
import yaml

# =============================================================================
# SECTION 1: SEMANTIC ANALYSIS - DANGEROUS FUNCTION CALLS
# =============================================================================

# 1.1 Code Injection Vulnerabilities (CRITICAL)
user_input = input("Enter command: ")
eval(user_input)  # CRITICAL: Code injection via eval
exec("print('hello')")  # CRITICAL: Code injection via exec

# 1.2 Deserialization Vulnerabilities (CRITICAL)
data = b"malicious pickle data"
pickle.loads(data)  # CRITICAL: Arbitrary code execution

unsafe_yaml = yaml.load("user_input")  # HIGH: Unsafe YAML loading

# 1.3 Command Injection (HIGH)
os.system("ls -la")  # HIGH: Command injection risk
os.popen("cat /etc/passwd")  # HIGH: Command injection risk
subprocess.call(["bash", "-c", "echo test"], shell=True)  # MEDIUM: Shell injection

# 1.4 Hardcoded Secrets (CRITICAL - Semantic Detection)
password = "SuperSecretPassword123!"  # CRITICAL: Hardcoded password
api_key = "sk-1234567890abcdef"  # CRITICAL: Hardcoded API key
secret_token = "ghp_abcdefghijklmnop123456"  # CRITICAL: Hardcoded token
private_key = "-----BEGIN RSA PRIVATE KEY-----"  # CRITICAL: Hardcoded private key

# =============================================================================
# SECTION 2: CODE COMPLEXITY METRICS
# =============================================================================

# 2.1 High Cyclomatic Complexity Function (Complexity > 10)
def extremely_complex_function(a, b, c, d, e, f):
    """This function has high cyclomatic complexity."""
    result = 0
    if a > 0:
        if b > 0:
            if c > 0:
                for i in range(10):
                    for j in range(10):
                        if i == j:
                            if i % 2 == 0:
                                while d > 0:
                                    if e > 0:
                                        if f > 0:
                                            result += 1
                                        else:
                                            result -= 1
                                    elif e < 0:
                                        result *= 2
                                    else:
                                        result /= 2
                                    d -= 1
                            elif i % 3 == 0:
                                result = result or a or b or c
                            else:
                                result = a and b and c and d
    return result

# 2.2 Technical Debt Indicators
# TODO: This needs to be refactored urgently
# FIXME: Critical bug that causes data loss
# HACK: Temporary workaround for database issue
# TODO: Remove this copied code
# FIXME: Replace with proper implementation
# HACK: Quick fix for production issue
# TODO: Implement proper error handling
# FIXME: Memory leak in this function
# HACK: Bypass security check temporarily
# TODO: Add unit tests
# FIXME: Race condition in multi-threaded scenario
# HACK: Workaround for API limitation

# =============================================================================
# SECTION 3: AI-GENERATED CODE DETECTION
# =============================================================================

# Generated by ChatGPT
# This function was written by Claude
# Copilot suggestion
# Auto-generated by GitHub Copilot
# Written by GPT-4

# This function takes input_data as a parameter and returns the processed result
def ai_generated_function(input_data):
    """
    This function processes the input data and returns a result.
    
    Args:
        input_data: The input data to be processed.
        
    Returns:
        The processed result after applying the transformation.
        
    Raises:
        ValueError: If the input is invalid.
        
    Example:
        result = ai_generated_function([1, 2, 3])
    """
    result_value = None
    output_result = []
    
    # The following code will process the data
    print("Starting processing...")
    
    try:
        result_value = input_data
    except Exception as e:
        # Handle the exception
        pass
    
    print("Completed processing")
    return result_value

# TODO: Implement the logic here
# TODO: Add the functionality below

# =============================================================================
# SECTION 4: CODE FRAUD DETECTION
# =============================================================================

# 4.1 License Violations
# MIT License - must include copyright notice
# Licensed under GPL-3.0 - copyleft requirements
# Apache License 2.0 - patent grants required
# Copyright (c) 2024 Example Corp - All rights reserved

# 4.2 Attribution Missing
# Based on https://github.com/example/repo
# Copied from stackoverflow.com
# Adapted from GitLab repository

# 4.3 Suspicious Patterns (TEST ONLY!)
# stolen_code_marker = None
# pirated_content = False
# cracked_version = "test"

# =============================================================================
# SECTION 5: NETHERLANDS-SPECIFIC PII
# =============================================================================

# BSN Numbers (Dutch Social Security)
bsn_number = "BSN: 123456789"
burgerservicenummer = "111222333"

# Dutch Financial Identifiers
dutch_iban = "IBAN NL91ABNA0417164300"
btw_nummer = "NL123456789B01"
kvk_number = "KvK: 12345678"

# Dutch Medical Data
# medische gegevens
# ziekenhuis records
# Patient data example

# =============================================================================
# EXPECTED DETECTION SUMMARY
# =============================================================================
"""
When scanning this file, expect:

1. SEMANTIC ANALYSIS (AST):
   - eval() injection: CRITICAL
   - exec() injection: CRITICAL  
   - pickle.loads() deserialization: CRITICAL
   - yaml.load() unsafe: HIGH
   - os.system() command injection: HIGH
   - os.popen() command injection: HIGH
   - subprocess.call() shell injection: MEDIUM
   - Hardcoded secrets (password, api_key, etc.): CRITICAL

2. CODE COMPLEXITY:
   - extremely_complex_function(): HIGH cyclomatic complexity (~15+)
   - Technical debt score: HIGH (12+ TODO/FIXME/HACK markers)

3. AI-GENERATED CODE:
   - ChatGPT/Claude/Copilot/GPT-4 markers: HIGH
   - AI-typical verbose comments: MEDIUM
   - AI variable naming patterns: MEDIUM

4. CODE FRAUD:
   - License markers: HIGH
   - Attribution missing: MEDIUM
   - Suspicious code patterns: CRITICAL

5. NETHERLANDS PII:
   - BSN numbers: CRITICAL
   - IBAN numbers: HIGH
   - BTW/VAT numbers: MEDIUM
   - KvK numbers: MEDIUM
   - Medical data references: HIGH
"""

if __name__ == "__main__":
    print("This is a test file for Advanced Code Analysis")
    print("Upload to DataGuardian Pro Code Scanner to test all detection features")
