"""
TEST FILE: Code Fraud & AI-Generated Code Detection
====================================================
Use this file to test the new Code Scanner detection features.
Upload or scan this file to see all detection categories in action.

IMPORTANT: This is a TEST FILE with intentional fraud/AI indicators.
DO NOT use this code in production!
"""

# =============================================================================
# SECTION 1: AI-GENERATED CODE DETECTION
# =============================================================================

# 1.1 Direct AI Attribution Markers (HIGH severity)
# Generated by ChatGPT
# written by Claude
# Created by GPT-4
# Copilot suggestion
# This code was generated by OpenAI
# Auto-generated by Copilot

# 1.2 AI Tool References (HIGH severity)
# Used GitHub Copilot for this implementation
# Cursor AI helped write this
# Amazon CodeWhisperer generated this function
# Tabnine autocomplete suggestion

# 1.3 AI-Typical Verbose Comments (MEDIUM severity)
# This function takes input_data as a parameter and returns the processed result
# The following code will process the data and output the result

def ai_style_function(input_data):
    """
    This function processes the input data and returns a result.
    
    Args:
        input_data: The input data to be processed. This should be a valid data structure.
        
    Returns:
        The processed result after applying the transformation logic.
        
    Raises:
        ValueError: If the input data is invalid or malformed.
        TypeError: If the input type is not supported.
        
    Example:
        result = ai_style_function([1, 2, 3])
        print(result)  # Output: [2, 4, 6]
    """
    result_value = None
    output_result = []
    
    # Starting processing
    print("Starting processing...")
    
    try:
        result_value = input_data
    except Exception as e:
        # Handle the exception
        pass
    
    # Completed processing
    print("Completed processing")
    return result_value

# 1.4 AI Placeholder Patterns (MEDIUM severity)
# TODO: Implement the logic here
# TODO: Add the functionality below
pass  # Placeholder

# =============================================================================
# SECTION 2: CODE FRAUD - LICENSE VIOLATIONS
# =============================================================================

# 2.1 License Markers (HIGH severity)
# MIT License
# Licensed under GPL-3.0
# Apache License 2.0
# Copyright (c) 2024 Example Corp
# All rights reserved
# This code is proprietary and confidential

# 2.2 Attribution References (MEDIUM severity)
# Based on https://github.com/example/repo
# Copied from stackoverflow: https://stackoverflow.com/questions/12345
# Adapted from GitLab repository
# Source: https://gist.github.com/user/code

# 2.3 License Compatibility Issues (HIGH severity)
# Note: GPL code mixed with proprietary - license conflict possible

# =============================================================================
# SECTION 3: CODE FRAUD - STOLEN CODE MARKERS
# =============================================================================

# 3.1 Suspicious Code Markers (CRITICAL severity)
# WARNING: These are test patterns only!
# stolen_code_example = "This is NOT real stolen code"
# pirated_check = False
# cracked_version = "test"
# keygen_sample = None
# decompiled_test = "sample"

# 3.2 License Bypass Patterns (CRITICAL severity)
# bypass_license_check = False  # Just a test variable name
# crack_protection = None  # Test pattern

# =============================================================================
# SECTION 4: CODE FRAUD - BACKDOOR INDICATORS
# =============================================================================

# 4.1 Network Patterns (CRITICAL severity - TEST ONLY!)
import socket
# reverse_shell_test = "nc -lp 4444"  # Commented test pattern
# backdoor_example = None  # Test variable

# 4.2 Command Execution Patterns (CRITICAL severity)
import subprocess
# subprocess.call(["bash", "-c", "echo test"])  # Safe test pattern

# =============================================================================
# SECTION 5: CODE FRAUD - OBFUSCATION INDICATORS
# =============================================================================

# 5.1 Obfuscation Markers (MEDIUM severity)
# obfuscated code sample
# minified version
# packed script

# 5.2 Suspicious Encodings (MEDIUM severity)
# Base64 eval pattern: eval(base64.decode('dGVzdA=='))
# Hex encoded: \x74\x65\x73\x74

# =============================================================================
# SECTION 6: CODE FRAUD - IP THEFT INDICATORS
# =============================================================================

# 6.1 Trade Secret Markers (CRITICAL severity)
# trade_secret_algorithm = None  # Test pattern
# proprietary_algorithm = "example"
# confidential_code = True

# 6.2 NDA References (CRITICAL severity)
# This code is under NDA - confidential implementation

# =============================================================================
# SECTION 7: CODE FRAUD - CODE DUPLICATION
# =============================================================================

# 7.1 Copy-Paste Indicators (LOW severity)
# TODO: remove this copied code
# FIXME: replace with original implementation
# duplicate code section
# temporary placeholder solution

# =============================================================================
# SECTION 8: NETHERLANDS-SPECIFIC PATTERNS (UAVG/GDPR)
# =============================================================================

# 8.1 BSN Numbers (Dutch Social Security) - CRITICAL
bsn_test = "BSN: 123456789"  # Test BSN pattern
burgerservicenummer = "111222333"

# 8.2 Dutch Financial Identifiers
iban_test = "IBAN NL91ABNA0417164300"  # Test Dutch IBAN
btw_nummer = "NL123456789B01"  # Test BTW/VAT number
kvk_nummer = "12345678"  # Test KvK number

# 8.3 Dutch Medical Data
# Patient data example (test only)
# medische gegevens
# ziekenhuis records

# =============================================================================
# HOW TO TEST
# =============================================================================
"""
To test these patterns:

1. Using the UI (New Scan page):
   - Go to New Scan → Code Scanner
   - Upload this file or paste the repository path
   - Run the scan and check the report

2. Using Python directly:
   
   from services.code_scanner import CodeScanner
   
   scanner = CodeScanner()
   results = scanner.scan_file('test_samples/test_code_fraud_detection.py')
   
   print(f"Total findings: {results['pii_count']}")
   for finding in results['pii_found']:
       print(f"  - {finding['type']}: {finding.get('value', '')[:50]}")
       print(f"    Severity: {finding.get('severity', finding.get('risk_level', 'Unknown'))}")
       print(f"    Compliance: {finding.get('compliance_reference', 'N/A')}")

3. Expected Detection Categories:
   - AI Generated Code: 10+ findings (HIGH)
   - AI Code Style Indicators: 5+ findings (MEDIUM)
   - License Violations: 5+ findings (HIGH)
   - Attribution Missing: 4+ findings (MEDIUM)
   - Backdoor Indicators: 2+ findings (CRITICAL)
   - Obfuscation Indicators: 3+ findings (MEDIUM)
   - Code Duplication: 4+ findings (LOW)
   - BSN/IBAN/BTW Detection: 5+ findings (CRITICAL/HIGH)
"""

if __name__ == "__main__":
    print("This is a test file for Code Fraud Detection")
    print("Upload to DataGuardian Pro Code Scanner to test all detection features")
